# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'my accelerometer Watch App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for my accelerometer Watch App

  target 'my accelerometer Watch AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'my accelerometer Watch AppUITests' do
    # Pods for testing
  end

end

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

